### ISSUE TITLE
[UAT-3] [Customer] User can become a Customer

### ISSUE THREAD

**Issue by rpgarde** [codesydney/migram-frontend#13]
Hello Tester,

Please add your comments here and we can discuss. 

### Current status
- [x] Testing started
- [x] Testing passed

**Comment by moises962** [comment]
I have tried the Become a Customer option, which takes me to the right screen. However after adding my details to Become a Customer, but there is no sign that it is being accepted.
When I go back to my Account screen I fo not have any confirmation that I am now a Customer.

**Comment by engramar** [comment]
FYI/A @s-sinadinovic @rpgarde @HDKHALILI . Thanks

**Comment by engramar** [comment]
@s-sinadinovic confirmed that there is a potential enhancement in this area but @moises962 is fine with the current implementation.

**Comment by engramar** [comment]
Enhancement request raised in #27
