### ISSUE TITLE
[UAT-4] [Customer] User is able to add a card

### ISSUE THREAD

**Issue by rpgarde** [codesydney/migram-frontend#14]
Hello Tester,

Please add your comments here and we can discuss. 

### Additional notes for tester
Test card to use 
card: 4242 4242 4242 4242 exp: 04/24 cvv: 242

### Current status
- [x] Testing started
- [x] Testing passed

**Comment by moises962** [comment]
Entering a random card number produces an error message.
When test card is entered correctly, there is no message to confirm that it has been accepted. It would be good to have a message to say card has been accepted.
Rgds,
Moises

**Comment by engramar** [comment]
FYI/A @s-sinadinovic @rpgarde @HDKHALILI

**Comment by engramar** [comment]
Enhancement raised as #29

**Comment by va-le-ria** [comment]
No issues now
