### ISSUE TITLE
[UAT-7] [Customer] User should be able to release payment after the actual job is done and marked as completed by the service provider

### ISSUE THREAD

**Issue by rpgarde** [codesydney/migram-frontend#17]
Hello Tester,

Please add your comments here and we can discuss. 

### Current status
- [x] Testing started
- [ ] Testing passed

**Comment by va-le-ria** [comment]
No issues until marking as completed as the service provider. I click it and nothing happens, when I click on the "completed" tab nothing happens. When I refresh the page nothing changes.

**Comment by engramar** [comment]
Defect raised as #30

**Comment by va-le-ria** [comment]
No issues now

**Comment by davidtaing** [comment]
As per the meeting on the 9th August 2022, we have decided to push back Payments for review at the next milestone.

This one is officially on hold for now.
