### ISSUE TITLE
[Customer] User can post a job (i.e. Create a task)

### ISSUE THREAD

**Issue by engramar** [codesydney/migram-frontend#179]
### Current status
- [x] Testing started
- [x] Testing ongoing
- [x] Testing passed

**Comment by engramar** [comment]
After clicking the 'Create Task' button, I can see all the fields below which is good. 
![image](https://user-images.githubusercontent.com/7553347/226199239-0dc8d1d3-9c48-492f-a337-c862eee2fb48.png)

**Comment by engramar** [comment]
![image](https://user-images.githubusercontent.com/7553347/226199330-56a5c6b0-2240-4525-8c19-7ad09a0f1438.png)

**Comment by engramar** [comment]
Looks like I got an exception around geo keys?
![image](https://user-images.githubusercontent.com/7553347/226199364-e6a6e80e-c322-4e84-ba7e-31617bcaff1f.png)

**Comment by davidtaing** [comment]
> Looks like I got an exception around geo keys? [image](https://user-images.githubusercontent.com/7553347/226199364-e6a6e80e-c322-4e84-ba7e-31617bcaff1f.png)

The backend might be on an old version. Original locations were stored as Geocodes, but I changed it to a standard address format. Will have a look when I get a chance.

**Comment by engramar** [comment]
Passed restesting. Thanks for the fix, @davidtaing  
![image](https://user-images.githubusercontent.com/7553347/227703278-a78da161-8435-4ee1-a19f-b4ce3f58e836.png)

**Comment by engramar** [comment]
I can also see the same posting when logged in as a provider. 
![image](https://user-images.githubusercontent.com/7553347/227703342-a25ab2e5-8cb9-4dc1-a0a2-bc9eda8627eb.png)
