### ISSUE TITLE
[Service Provider] User is able to sign up

### ISSUE THREAD

**Issue by engramar** [codesydney/migram-frontend#182]
### Current status
- [x] Testing started
- [x] Testing ongoing
- [x] Testing passed

**Comment by engramar** [comment]
Looks good. I like how the signup link for providers is presented as there will be some handholding anyway.
![image](https://user-images.githubusercontent.com/7553347/226425524-74881813-9d1b-4400-963d-b23251206a9e.png)

**Comment by engramar** [comment]
Looks good. I like how the sign up link for providers is presented particularly as they need some handholding first. 
![image](https://user-images.githubusercontent.com/7553347/226425793-0602700a-a1b7-4751-b8ba-8905bfddfc1d.png)

**Comment by engramar** [comment]
I can see that it is still connected to Praveen's Stripe test environment. 
![image](https://user-images.githubusercontent.com/7553347/226426108-b61c2408-fa34-45e2-87a4-db5da85f9b8b.png)

**Comment by engramar** [comment]
After confirming the above and submitting the Stripe application, I got a 404 
![image](https://user-images.githubusercontent.com/7553347/226429039-cd1db134-a9a6-429c-8184-7163f3d34b79.png)

**Comment by engramar** [comment]
After getting the 404, the service provider seems to have been logged in but can't see any listing. I have to logout and login again to see the listings to make an offer.

**Comment by davidtaing** [comment]
The 404 is a coming from a redirect to `URL/account` which is a deleted page. I think this needs to be configured in both Stripe and the Express Server

**Comment by davidtaing** [comment]
Found another issue where after the Stripe onboarding is completed, the user becomes orphaned and is neither a `Provider` or a `Customer` user.

I looked into this before and have a good idea about what is causing it. I had updated the create Provider endpoint to create an Express account and thought this was resolved. (I'll look into that a bit later)

**Comment by engramar** [comment]
Cheers @davidtaing, Will just wait for the fix to retest.

**Comment by davidtaing** [comment]
Should be ready to test

**Comment by engramar** [comment]
Thanks @davidtaing

**Comment by engramar** [comment]
404 is gone now. Managed to successfully onboard a new service provider. Thanks again @davidtaing
