### ISSUE TITLE
[General] Burger icon does not seem to do anything

### ISSUE THREAD

**Issue by engramar** [codesydney/migram-frontend#191]
### Current status
- [x] Testing started
- [x] Testing ongoing
- [x] Testing passed

![image](https://user-images.githubusercontent.com/7553347/227705843-bf1f71d1-34e7-460f-ad24-2dd37faf61c8.png)

**Comment by davidtaing** [comment]
This has been fixed. It will now trigger the mobile navigation menu to appear

**Comment by engramar** [comment]
All good now @davidtaing. Thanks. 
![image](https://user-images.githubusercontent.com/7553347/229899056-b472dd04-0d7d-452b-9851-bb8979004b7b.png)
