### ISSUE TITLE
[UAT-12] [Service Provider] User can mark the Offer as completed after the actual Task is done

### ISSUE THREAD

**Issue by rpgarde** [codesydney/migram-frontend#22]
Hello Tester,

Please add your comments here and we can discuss. 

### Current status
- [ ] Testing started
- [ ] Testing passed

**Comment by davidtaing** [comment]
I've renamed the issue to match the names that were used in the project for better clarity.

**Comment by davidtaing** [comment]
This one isn't complete yet and I do think this is a higher priority task.

Reopening this task for now.

**Comment by engramar** [comment]
Thanks @davidtaing, I added it in scope for soft launch. by adding the relevant label.
