### ISSUE TITLE
Customer (with a valid email account) should receive emails from the Migram system

### ISSUE THREAD

**Issue by seqprav** [codesydney/migram-frontend#26]
Hi @moises962 , @va-le-ria  cc: @engramar 

I've now integrated the backend to use SendGrid (my own account). This means the following:

If you have registered a customer with a REAL email account, then as a part of your testing, posing as as a customer, you can login to that email account and receive emails when the below events happen:

a) new offer is received from the service provider
b) payment made by the customer is successful or unsuccessful

**Comment by engramar** [comment]
Thanks mate @seqprav . Cheers.
