### ISSUE TITLE
[UAT Finding per UAT-3] No confirmation after choosing to become a customer

### ISSUE THREAD

**Issue by engramar** [codesydney/migram-frontend#27]
Per @moises962 

> I have tried the Become a Customer option, which takes me to the right screen. However after adding my details to Become a Customer, but there is no sign that it is being accepted.
When I go back to my Account screen I do not have any confirmation that I am now a Customer.

**Comment by rpgarde** [comment]
@moises962 @engramar I have pushed an update that adds a confirmation upon becoming a customer.

Can you please verify if this resolves the issue and if so, feel free to Close the issue. Thanks!

<img width="262" alt="image" src="https://user-images.githubusercontent.com/80566196/162654451-56c91b18-57f7-45b9-a22d-6ccdbfde7b83.png">

**Comment by davidtaing** [comment]
Hi @engramar & @moises962, just wanted to check if you had the chance to review the changes yet?

It looks like it is complete, but we were waiting on confirmation.
