### ISSUE TITLE
The submit button doesn't work when creating a job request

### ISSUE THREAD

**Issue by ettienekorayyi** [codesydney/migram-frontend#37]
Summary:
When the customer tries to submit a new job post by clicking the submit button on the left side of the page the button doesn't work

Screenshot:
![image](https://user-images.githubusercontent.com/19362078/182005700-b6d7059c-4569-49dd-83ce-7f2f30b0b765.png)

**Comment by engramar** [comment]
Thanks @ettienekorayyi, I managed to replicate it and you are correct. It does not do anything so we just need to hide this button. 

![image](https://user-images.githubusercontent.com/7553347/185089680-6e527d5c-541f-4518-b79b-1dd73b1b62fa.png)

**Comment by engramar** [comment]
I assigned it to myself. Let me try and see if I can tweak this. 😊

**Comment by davidtaing** [comment]
@engramar I think it's better to remove the submit button rather than hide it as we already have a submit button on the right. Let us know how you go. 👌

**Comment by engramar** [comment]
Thanks @davidtaing. I just commented it for now. 
Done and deployed to production. 
![image](https://user-images.githubusercontent.com/7553347/186394194-f61d911e-ce07-40c3-9402-328bc6848402.png)
