### ISSUE TITLE
Bug(BE): POST /users/signup - Creates a New User When Name is Not Provided

### ISSUE THREAD

**Issue by davidtaing** [codesydney/migram-frontend#38]
**Describe the bug**
POST /users/signup allows users to signup when Name is missing from the request body.

**To Reproduce**
1. Make a POST Request to /users/signup with the following body:
`{
    "email": "postman@email.com",
    "password": "password",
    "passwordConfirm": "password"
}`
2. See error.

Note: I've already created this user so the error message returned refers to the email already being in use.

**Expected behavior**
HTTP 400 Error with Missing Name Message?

**Screenshots**
<img width="1440" alt="POST :users:signup - No Name" src="https://user-images.githubusercontent.com/8443215/182013925-67bc0686-58fa-439a-847c-cb72f7ff7b95.png">

## Solution
- Add a check for req.body.name and respond with an error if one is not provided.

**Comment by engramar** [comment]
Thanks David, We can postpone this for the final milestone. Cheers.
