### ISSUE TITLE
Bug(BE) - PasswordConfirm Saved to User Documents

### ISSUE THREAD

**Issue by davidtaing** [codesydney/migram-frontend#39]
**Describe the bug**

**To Reproduce**
1. Make PUT request to /users/:userid
2. Inspect the returned user object.

**Expected behavior**
PasswordConfirm should not be persisted in the database.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8443215/182015227-970d1bac-888d-4e2f-9a24-84f3a4801c41.png">

## Potential Solution
- Move the confirm password matches password check to the controller. This way we remove the field in the Mongoose Model but still perform the check.

**Comment by engramar** [comment]
Thanks David, We can postpone this for the final milestone. There is not that much risk exposure during the soft launch as we will not store any credit card info or even accept payment as yet.

**Comment by davidtaing** [comment]
Hi @engramar, I have discussed this with Praveen in the past and he does not consider this as an issue.

I'll close this one for now.
