### ISSUE TITLE
Bug(BE) - PUT /users/:id Allows Update With No Body

### ISSUE THREAD

**Issue by davidtaing** [codesydney/migram-frontend#40]
**Describe the bug**
PUT /users/:id Allows Update With No Body. PUT requests require the entire object to be submitted where as the internal implementation behaves more like a PATCH request which allows a partial update.

See: [https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT)

**To Reproduce**
1. Make a PUT request to /users/:id with no body and Authorization token
`Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZTUxZGM4ODcwYWVmMDAxNjUwZDE1YSIsImlhdCI6MTY1OTI1MTExNH0.nBjzz4KD4H-HhANeqE4Qgu2V2EKyYTEicMHSF836ci4`
3. View response.

**Expected behavior**
Returns HTTP 400 Bad Request Error. In my opinion, this should reject with a 400 error. The route shouldn't allow an update operation with nothing to update.

**Actual behavior**
Returns a HTTP 200 OK Response.

**Screenshots**

Input: No Request Body
<img width="1440" alt="Screen Shot 2022-07-31 at 5 34 45 pm" src="https://user-images.githubusercontent.com/8443215/182015663-8694e155-f4cd-416e-8004-9f5800260ed8.png">

Input: Empty Request Body
<img width="1440" alt="Screen Shot 2022-07-31 at 5 52 35 pm" src="https://user-images.githubusercontent.com/8443215/182015795-83f8337f-3a1a-4987-804d-e4cdf3deda8e.png">

## Solution

- Add a check for a request body in the controller.

**Comment by engramar** [comment]
Hello @davidtaing , As this is more of a direct API call and not via UI, I will just postpone this for the final milestone instead of scoping for the soft launch. Thanks.
