### ISSUE TITLE
As per Steve: Hide the 'get started' button

### ISSUE THREAD

**Issue by engramar** [codesydney/migram-frontend#41]
As observed by Steve, nothing is happening when clicking the 'get started' button. Let us hide this button instead. 
![image](https://user-images.githubusercontent.com/7553347/185088004-2cafff87-a748-4d57-96e5-c7861afc686e.png)

**Comment by davidtaing** [comment]
If you want to hide the button and leave the implementation, you can do this one with CSS.

```css
display: hidden;
```

It's kinda bad to use inline styles, but you can set the styles prop. I'd prefer to use a global CSS file, but we don't have one here.

```js
styles={{
  display: "hidden"
}}
```

Add a class
https://github.com/codesydney/migram-frontend/blob/425b52baaed59508692aa57d91eb6e4b3d06023c/components/account/Landing.tsx#L37

**Comment by engramar** [comment]
Done and deployed to production. 
![image](https://user-images.githubusercontent.com/7553347/186393724-c7e03603-7f28-416b-a8d6-c07d9fe76a3c.png)
