### ISSUE TITLE
Bug: [Provider] Clicking on OfferItem Refetches All Offers

### ISSUE THREAD

**Issue by davidtaing** [codesydney/migram-frontend#43]
# Description
Clicking on an OfferItem requests all offer data. In my opinion, this is an unnecessary request to the backend as the data has not changed in most situations. The exception is when an "Open" Offer can be accepted by the Customer, which causes a change in the data. But I think it's best for the user to refresh the page.

This is a minor issue at the moment and can be pushed back for review at a later date.

## Expected Behaviour

1. Highlights the selected OfferItem
2. Does not make a request to the backend when an OfferItem is clicked.

## Actual Behaviour

1. Highlights the selected OfferItem
2. Requests and fetches all Offers again.

## Screenshots
![C0eMd0sOml](https://user-images.githubusercontent.com/8443215/186103775-dd8b3f07-0f90-47d1-9e80-5fc1c737f3de.gif)

## To Reproduce

1. Sign is as a Provider
2. Go to the offers page: [https://www.migram.com.au/offers](https://www.migram.com.au/offers)
3. Open your Browser DevTools by pressing F12
4. Click on the OfferItem and see the console log the tasks again.

**Comment by engramar** [comment]
Good catch @davidtaing, Since we do not have that many transactions during soft launch, we will just scope this as part of the final milestone. Managed to replicate the issue from here. 
![image](https://user-images.githubusercontent.com/7553347/186511510-58086ba9-6d2c-49c1-9daa-7bf4cf33c9a1.png)
