### ISSUE TITLE
Bug: HomePage Refreshes Session Upon Rerenders

### ISSUE THREAD

**Issue by davidtaing** [codesydney/migram-frontend#46]
# Description
The HomePage makes a request to refresh the Auth session every time the page renders.

## Expected Behaviour

1. Session gets updated once when the HomePage component mounts.

## Actual Behaviour

1. Session was updated 8 times upon a page refresh.

## Screenshot

<img width="960" alt="chrome_LVIx3xl6QK" src="https://user-images.githubusercontent.com/8443215/186417363-2b120243-ca4c-4a22-b8ea-b6ad3cfaeb5d.png">

## To Reproduce

1. Go to the Migram homepage
2. Login using any account
3. Open your browser's DevTools
4. View the console.logs

Note: The code logs "updated credentials" whenever the request is made.

## Files

https://github.com/codesydney/migram-frontend/blob/f7f32cc6e6407b4349eaa9cc89e9297139d05ae3/pages/index.tsx#L5-L14

**Comment by CapSap** [comment]
Hey David I'll have a crack

**Comment by CapSap** [comment]
My intuition is the move the axois.get inside of a useEffect hook and set the dependency to an empty array. But I don't understand why the component is being re-rendered 8 times and can't articulate why this is happening.

**Comment by davidtaing** [comment]
> My intuition is the move the axois.get inside of a useEffect hook and set the dependency to an empty array. But I don't understand why the component is being re-rendered 8 times and can't articulate why this is happening.

Well done in using the useEffect hook to fix this issue. It looks like when you refresh the session, the expiry time changes and is counted as a state update. We rerender every time the props or state changes.

![image](https://user-images.githubusercontent.com/8443215/187598345-03146f64-d9fc-4646-83bb-c457d15978ec.png)
