### ISSUE TITLE
Bug: Sign Up Button Cannot Be Clicked on Homepage on Viewports < 820px Width

### ISSUE THREAD

**Issue by davidtaing** [codesydney/migram-frontend#48]
# Description

On viewports, less than 820 px in width, the "Sign Up" button cannot be clicked on the Homepage. The IMS Banner appears to be sitting on top of most of the button. Note: Clicking at the very top of the button still works, but clicking on the lower half doesn't.

**Severity: Minor**

## Expected Behavior

- When the button is clicked, the app should navigate to the sign up page.

## Actual Behavior

- The button is unresponsive to clicks and nothing happens.

## Screenshots

![j2UoU7ye27](https://user-images.githubusercontent.com/8443215/186822249-7bf7969e-7794-4535-967b-b78e302cf7ba.jpg)

## To Reproduce

1. Navigate to the homepage.
2. Open your browser's DevTools.
3. Click on the "Toggle Device Toolbar" in Chrome or the "Responsive Design Mode" in Firefox.
4. Select a viewport less than 820 pixels wide.
5. Try to click on the button (in the lower half is preferred).

**Comment by MReyna12** [comment]
Hello David,

Unless someone else is already tackling this bug, I'd appreciate an opportunity to take care of it.

Thanks!

**Comment by MReyna12** [comment]
Please ignore the original PR. Was having some issues with the package.lock.json earlier. New PR contains just the commit related to fixing the bug.

Please let me know if you have any questions!

**Comment by davidtaing** [comment]
Hey Michael,
I might to have break your heart, but the project might be for Australians only. I have to double check with the team leads and get back to you in a few days (maybe Monday or Tuesday).

I'll be happy to review your pull request in the meantime and credit you as a contributor.

Having said that, I wanted to sincerly thank you for helping us out. Contributing to Open Source is something that I have personally wanted to do for a while now and I know that it's hard getting started. You've haven't done anything wrong. You've done really well at putting yourself out there.

Regards,
Dave

**Comment by MReyna12** [comment]
Thanks for the quick reply, David. No rush at all and thanks so much for letting me know. 

I also appreciate the kind words.

If it turns out I can be of any help, happy to do so. However, if the project is limited to Australians only, then I wish you all the best of luck!

Enjoy your weekend.

Thanks,

Michael

**Comment by davidtaing** [comment]
Hi Michael,
The team leads have gotten back to me, unfortunately, the project will be for Australians only. Sorry to give you the bad news.

**Comment by MReyna12** [comment]
No problem. I've closed my PR. Best of luck with the project!
